// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: math.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_math_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_math_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_math_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_math_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_math_2eproto;
namespace mypackage {
class MathRequest;
struct MathRequestDefaultTypeInternal;
extern MathRequestDefaultTypeInternal _MathRequest_default_instance_;
class MathResponse;
struct MathResponseDefaultTypeInternal;
extern MathResponseDefaultTypeInternal _MathResponse_default_instance_;
}  // namespace mypackage
PROTOBUF_NAMESPACE_OPEN
template<> ::mypackage::MathRequest* Arena::CreateMaybeMessage<::mypackage::MathRequest>(Arena*);
template<> ::mypackage::MathResponse* Arena::CreateMaybeMessage<::mypackage::MathResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mypackage {

// ===================================================================

class MathRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mypackage.MathRequest) */ {
 public:
  inline MathRequest() : MathRequest(nullptr) {}
  ~MathRequest() override;
  explicit PROTOBUF_CONSTEXPR MathRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MathRequest(const MathRequest& from);
  MathRequest(MathRequest&& from) noexcept
    : MathRequest() {
    *this = ::std::move(from);
  }

  inline MathRequest& operator=(const MathRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MathRequest& operator=(MathRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MathRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MathRequest* internal_default_instance() {
    return reinterpret_cast<const MathRequest*>(
               &_MathRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MathRequest& a, MathRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(MathRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MathRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MathRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MathRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MathRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MathRequest& from) {
    MathRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MathRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mypackage.MathRequest";
  }
  protected:
  explicit MathRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMatrixAFieldNumber = 1,
    kMatrixBFieldNumber = 2,
  };
  // repeated float matrix_a = 1;
  int matrix_a_size() const;
  private:
  int _internal_matrix_a_size() const;
  public:
  void clear_matrix_a();
  private:
  float _internal_matrix_a(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_matrix_a() const;
  void _internal_add_matrix_a(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_matrix_a();
  public:
  float matrix_a(int index) const;
  void set_matrix_a(int index, float value);
  void add_matrix_a(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      matrix_a() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_matrix_a();

  // repeated float matrix_b = 2;
  int matrix_b_size() const;
  private:
  int _internal_matrix_b_size() const;
  public:
  void clear_matrix_b();
  private:
  float _internal_matrix_b(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_matrix_b() const;
  void _internal_add_matrix_b(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_matrix_b();
  public:
  float matrix_b(int index) const;
  void set_matrix_b(int index, float value);
  void add_matrix_b(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      matrix_b() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_matrix_b();

  // @@protoc_insertion_point(class_scope:mypackage.MathRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > matrix_a_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > matrix_b_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_math_2eproto;
};
// -------------------------------------------------------------------

class MathResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mypackage.MathResponse) */ {
 public:
  inline MathResponse() : MathResponse(nullptr) {}
  ~MathResponse() override;
  explicit PROTOBUF_CONSTEXPR MathResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MathResponse(const MathResponse& from);
  MathResponse(MathResponse&& from) noexcept
    : MathResponse() {
    *this = ::std::move(from);
  }

  inline MathResponse& operator=(const MathResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MathResponse& operator=(MathResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MathResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const MathResponse* internal_default_instance() {
    return reinterpret_cast<const MathResponse*>(
               &_MathResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MathResponse& a, MathResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(MathResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MathResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MathResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MathResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MathResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MathResponse& from) {
    MathResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MathResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mypackage.MathResponse";
  }
  protected:
  explicit MathResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultMatrixFieldNumber = 1,
  };
  // repeated float result_matrix = 1;
  int result_matrix_size() const;
  private:
  int _internal_result_matrix_size() const;
  public:
  void clear_result_matrix();
  private:
  float _internal_result_matrix(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_result_matrix() const;
  void _internal_add_result_matrix(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_result_matrix();
  public:
  float result_matrix(int index) const;
  void set_result_matrix(int index, float value);
  void add_result_matrix(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      result_matrix() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_result_matrix();

  // @@protoc_insertion_point(class_scope:mypackage.MathResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > result_matrix_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_math_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MathRequest

// repeated float matrix_a = 1;
inline int MathRequest::_internal_matrix_a_size() const {
  return _impl_.matrix_a_.size();
}
inline int MathRequest::matrix_a_size() const {
  return _internal_matrix_a_size();
}
inline void MathRequest::clear_matrix_a() {
  _impl_.matrix_a_.Clear();
}
inline float MathRequest::_internal_matrix_a(int index) const {
  return _impl_.matrix_a_.Get(index);
}
inline float MathRequest::matrix_a(int index) const {
  // @@protoc_insertion_point(field_get:mypackage.MathRequest.matrix_a)
  return _internal_matrix_a(index);
}
inline void MathRequest::set_matrix_a(int index, float value) {
  _impl_.matrix_a_.Set(index, value);
  // @@protoc_insertion_point(field_set:mypackage.MathRequest.matrix_a)
}
inline void MathRequest::_internal_add_matrix_a(float value) {
  _impl_.matrix_a_.Add(value);
}
inline void MathRequest::add_matrix_a(float value) {
  _internal_add_matrix_a(value);
  // @@protoc_insertion_point(field_add:mypackage.MathRequest.matrix_a)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MathRequest::_internal_matrix_a() const {
  return _impl_.matrix_a_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MathRequest::matrix_a() const {
  // @@protoc_insertion_point(field_list:mypackage.MathRequest.matrix_a)
  return _internal_matrix_a();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MathRequest::_internal_mutable_matrix_a() {
  return &_impl_.matrix_a_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MathRequest::mutable_matrix_a() {
  // @@protoc_insertion_point(field_mutable_list:mypackage.MathRequest.matrix_a)
  return _internal_mutable_matrix_a();
}

// repeated float matrix_b = 2;
inline int MathRequest::_internal_matrix_b_size() const {
  return _impl_.matrix_b_.size();
}
inline int MathRequest::matrix_b_size() const {
  return _internal_matrix_b_size();
}
inline void MathRequest::clear_matrix_b() {
  _impl_.matrix_b_.Clear();
}
inline float MathRequest::_internal_matrix_b(int index) const {
  return _impl_.matrix_b_.Get(index);
}
inline float MathRequest::matrix_b(int index) const {
  // @@protoc_insertion_point(field_get:mypackage.MathRequest.matrix_b)
  return _internal_matrix_b(index);
}
inline void MathRequest::set_matrix_b(int index, float value) {
  _impl_.matrix_b_.Set(index, value);
  // @@protoc_insertion_point(field_set:mypackage.MathRequest.matrix_b)
}
inline void MathRequest::_internal_add_matrix_b(float value) {
  _impl_.matrix_b_.Add(value);
}
inline void MathRequest::add_matrix_b(float value) {
  _internal_add_matrix_b(value);
  // @@protoc_insertion_point(field_add:mypackage.MathRequest.matrix_b)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MathRequest::_internal_matrix_b() const {
  return _impl_.matrix_b_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MathRequest::matrix_b() const {
  // @@protoc_insertion_point(field_list:mypackage.MathRequest.matrix_b)
  return _internal_matrix_b();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MathRequest::_internal_mutable_matrix_b() {
  return &_impl_.matrix_b_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MathRequest::mutable_matrix_b() {
  // @@protoc_insertion_point(field_mutable_list:mypackage.MathRequest.matrix_b)
  return _internal_mutable_matrix_b();
}

// -------------------------------------------------------------------

// MathResponse

// repeated float result_matrix = 1;
inline int MathResponse::_internal_result_matrix_size() const {
  return _impl_.result_matrix_.size();
}
inline int MathResponse::result_matrix_size() const {
  return _internal_result_matrix_size();
}
inline void MathResponse::clear_result_matrix() {
  _impl_.result_matrix_.Clear();
}
inline float MathResponse::_internal_result_matrix(int index) const {
  return _impl_.result_matrix_.Get(index);
}
inline float MathResponse::result_matrix(int index) const {
  // @@protoc_insertion_point(field_get:mypackage.MathResponse.result_matrix)
  return _internal_result_matrix(index);
}
inline void MathResponse::set_result_matrix(int index, float value) {
  _impl_.result_matrix_.Set(index, value);
  // @@protoc_insertion_point(field_set:mypackage.MathResponse.result_matrix)
}
inline void MathResponse::_internal_add_result_matrix(float value) {
  _impl_.result_matrix_.Add(value);
}
inline void MathResponse::add_result_matrix(float value) {
  _internal_add_result_matrix(value);
  // @@protoc_insertion_point(field_add:mypackage.MathResponse.result_matrix)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MathResponse::_internal_result_matrix() const {
  return _impl_.result_matrix_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MathResponse::result_matrix() const {
  // @@protoc_insertion_point(field_list:mypackage.MathResponse.result_matrix)
  return _internal_result_matrix();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MathResponse::_internal_mutable_result_matrix() {
  return &_impl_.result_matrix_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MathResponse::mutable_result_matrix() {
  // @@protoc_insertion_point(field_mutable_list:mypackage.MathResponse.result_matrix)
  return _internal_mutable_result_matrix();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mypackage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_math_2eproto
