// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: math.proto

#include "math.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mypackage {
PROTOBUF_CONSTEXPR MathRequest::MathRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.matrix_a_)*/{}
  , /*decltype(_impl_.matrix_b_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathRequestDefaultTypeInternal() {}
  union {
    MathRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathRequestDefaultTypeInternal _MathRequest_default_instance_;
PROTOBUF_CONSTEXPR MathResponse::MathResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_matrix_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MathResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MathResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MathResponseDefaultTypeInternal() {}
  union {
    MathResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MathResponseDefaultTypeInternal _MathResponse_default_instance_;
}  // namespace mypackage
static ::_pb::Metadata file_level_metadata_math_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_math_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_math_2eproto = nullptr;

const uint32_t TableStruct_math_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mypackage::MathRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mypackage::MathRequest, _impl_.matrix_a_),
  PROTOBUF_FIELD_OFFSET(::mypackage::MathRequest, _impl_.matrix_b_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mypackage::MathResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mypackage::MathResponse, _impl_.result_matrix_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mypackage::MathRequest)},
  { 8, -1, -1, sizeof(::mypackage::MathResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mypackage::_MathRequest_default_instance_._instance,
  &::mypackage::_MathResponse_default_instance_._instance,
};

const char descriptor_table_protodef_math_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nmath.proto\022\tmypackage\"1\n\013MathRequest\022\020"
  "\n\010matrix_a\030\001 \003(\002\022\020\n\010matrix_b\030\002 \003(\002\"%\n\014Ma"
  "thResponse\022\025\n\rresult_matrix\030\001 \003(\0022Q\n\013Mat"
  "hService\022B\n\rComputeMatrix\022\026.mypackage.Ma"
  "thRequest\032\027.mypackage.MathResponse\"\000b\006pr"
  "oto3"
  ;
static ::_pbi::once_flag descriptor_table_math_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_math_2eproto = {
    false, false, 204, descriptor_table_protodef_math_2eproto,
    "math.proto",
    &descriptor_table_math_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_math_2eproto::offsets,
    file_level_metadata_math_2eproto, file_level_enum_descriptors_math_2eproto,
    file_level_service_descriptors_math_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_math_2eproto_getter() {
  return &descriptor_table_math_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_math_2eproto(&descriptor_table_math_2eproto);
namespace mypackage {

// ===================================================================

class MathRequest::_Internal {
 public:
};

MathRequest::MathRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mypackage.MathRequest)
}
MathRequest::MathRequest(const MathRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MathRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.matrix_a_){from._impl_.matrix_a_}
    , decltype(_impl_.matrix_b_){from._impl_.matrix_b_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mypackage.MathRequest)
}

inline void MathRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.matrix_a_){arena}
    , decltype(_impl_.matrix_b_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MathRequest::~MathRequest() {
  // @@protoc_insertion_point(destructor:mypackage.MathRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MathRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.matrix_a_.~RepeatedField();
  _impl_.matrix_b_.~RepeatedField();
}

void MathRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MathRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mypackage.MathRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.matrix_a_.Clear();
  _impl_.matrix_b_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MathRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float matrix_a = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_matrix_a(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 13) {
          _internal_add_matrix_a(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated float matrix_b = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_matrix_b(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 21) {
          _internal_add_matrix_b(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MathRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mypackage.MathRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float matrix_a = 1;
  if (this->_internal_matrix_a_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_matrix_a(), target);
  }

  // repeated float matrix_b = 2;
  if (this->_internal_matrix_b_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_matrix_b(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mypackage.MathRequest)
  return target;
}

size_t MathRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mypackage.MathRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float matrix_a = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_matrix_a_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated float matrix_b = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_matrix_b_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MathRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MathRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MathRequest::GetClassData() const { return &_class_data_; }


void MathRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MathRequest*>(&to_msg);
  auto& from = static_cast<const MathRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mypackage.MathRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.matrix_a_.MergeFrom(from._impl_.matrix_a_);
  _this->_impl_.matrix_b_.MergeFrom(from._impl_.matrix_b_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MathRequest::CopyFrom(const MathRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mypackage.MathRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MathRequest::IsInitialized() const {
  return true;
}

void MathRequest::InternalSwap(MathRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.matrix_a_.InternalSwap(&other->_impl_.matrix_a_);
  _impl_.matrix_b_.InternalSwap(&other->_impl_.matrix_b_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MathRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_math_2eproto_getter, &descriptor_table_math_2eproto_once,
      file_level_metadata_math_2eproto[0]);
}

// ===================================================================

class MathResponse::_Internal {
 public:
};

MathResponse::MathResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mypackage.MathResponse)
}
MathResponse::MathResponse(const MathResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MathResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_matrix_){from._impl_.result_matrix_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mypackage.MathResponse)
}

inline void MathResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_matrix_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MathResponse::~MathResponse() {
  // @@protoc_insertion_point(destructor:mypackage.MathResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MathResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.result_matrix_.~RepeatedField();
}

void MathResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MathResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mypackage.MathResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_matrix_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MathResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float result_matrix = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_result_matrix(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 13) {
          _internal_add_result_matrix(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MathResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mypackage.MathResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float result_matrix = 1;
  if (this->_internal_result_matrix_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_result_matrix(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mypackage.MathResponse)
  return target;
}

size_t MathResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mypackage.MathResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float result_matrix = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_result_matrix_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MathResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MathResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MathResponse::GetClassData() const { return &_class_data_; }


void MathResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MathResponse*>(&to_msg);
  auto& from = static_cast<const MathResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mypackage.MathResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.result_matrix_.MergeFrom(from._impl_.result_matrix_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MathResponse::CopyFrom(const MathResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mypackage.MathResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MathResponse::IsInitialized() const {
  return true;
}

void MathResponse::InternalSwap(MathResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.result_matrix_.InternalSwap(&other->_impl_.result_matrix_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MathResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_math_2eproto_getter, &descriptor_table_math_2eproto_once,
      file_level_metadata_math_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mypackage
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mypackage::MathRequest*
Arena::CreateMaybeMessage< ::mypackage::MathRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mypackage::MathRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mypackage::MathResponse*
Arena::CreateMaybeMessage< ::mypackage::MathResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mypackage::MathResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
