# See https://docs.astral.sh/ruff/configuration/
# For a full list of supported rules, see https://docs.astral.sh/ruff/rules/
# For a full list of options, see https://docs.astral.sh/ruff/settings/

target-version = "py39"

[lint]
ignore = [
    "I001",
    "RUF022",
    "UP035",
    "D413",
    "D401",
    "COM812",
    "RSE102",
    "F401",
    "B027",
    "ANN001",
    "C408",
    "ANN202",
    "UP032",
    "YTT203",
    "PLR2004",
    "UP006",
    "PLR0913",
    "E501",
    "SLF001",
    "FBT001",
    "FBT002",
    "D205",
    "ANN204",
    "TRY004",
    "C901",
    "PLR0912",
    "FIX002",
    "TD003",
    "S101",
    "SIM102",
    "TRY003",
    "TD004",
    "RET507",
    "EM102",
    "RET505",
    "D415",
    "D400",
    "ARG002",
    "PYI045",
    "B904",
    "PYI024",
    "B024",
    "PLW2901",
    "RET506",
    "D417",
    "D202",
    "PERF203",
    "E722",
    "D404",
    "PLW1641",
    "ANN206",
    "UP030",
    "EM103",
    "ANN401",
    "PYI032",
    "D104",
    "ANN201",
    "UP004",
    "D107",
    "UP004",
    "PLC0415",
    "FBT003",
    "ANN002",
    "EM101",
    "D411",
    "ISC003",
    "UP008",
    "D410",
    "FIX004",
    "BLE001",
    "LOG015",
    "PLR5501",
    "RET503",
    "RUF023",
    "D212",
    "S110",
    "TC001",
    "E731",
    "D213",
    "TRY400",
    "ERA001",
    "SIM105",
    "B007",
    "PLW0603",
    "UP037",
    "TRY300",
    "UP031",
    "F811",
    "S105",
    "ARG001",
    "RET504",
    "SIM118",
    "ANN205",
    "ARG001",
    "PLR0911",
    "PLR1711",
    "RET501",
    "UP036",
    "PLE0604",
    "RUF005",
    "TRY002",
    "TRY401",
    "ARG005",
    "DTZ005",
    "G003",
    "D103",
    "ANN003",
    "F403",
    "PYI006",
    "D105",
    "N818",
    "SIM910",
    "D102",
    "D106",
    "SLOT002",
    "PIE796",
    "A001",
    "N802",
    "E713",
    "PLC0206",
    "SIM108",
    "SIM300",
    "PYI056",
    "F821",
    "PTH123",
    "PLW1508",
    "UP015",
    "SIM114",
    "PERF401",
    "D200",
    "PERF102",
    "ARG004",
    "UP010",
    "FURB188",
    "D209",
    "UP010",
    "UP028",
    "ICN001",
    "D209",
    "A002",
    "PT015",
    "B011",
    "D209",
    "D207",
    "F841",
    "F523",
    "UP010",
    "UP018",
    "SIM115",
    "PLR0915",
    "C402",
    "TRY203",
    "D101",
    "D100",
    "PTH110",
    "D101",
    "PT027",
    "S603",
    "PLW0120",
    "PLR1704",
    "PT027",
    "PT009",
    "INP001",
    "PT017",
    "RUF013",
    "F541",
    "N803",
    "E402",
    "SIM103",
    "N806",
    "SIM103",
    "PTH118",
    "PTH120",
    "PTH103",
    "B018",
    "PTH103",
    "SIM117",
    "S311",
    "S301",
    "PT028",
    "DTZ001",
    "PTH100",
    "TC003",
    "T201",
    "TD005",
    "PTH107",
    "D403",
    "TD005",
    "C405",
    "UP024",
    "PLR1714",
    "YTT201",
    "FLY002"
]

# This is to suppress
# https://docs.astral.sh/ruff/rules/non-pep585-annotation/
# https://docs.astral.sh/ruff/rules/non-pep604-annotation-union/#non-pep604-annotation-union-up007
pyupgrade.keep-runtime-typing = true

# Select all rules by default, and then ignore the ones we don't want.
# This is a good way to stay up-to-date with new rules in ruff.
select = ["ALL"]

[format]
# Exclude all files from the formatter using a glob pattern.
# This is the most straightforward way to disable it.
exclude = ["*"]
